name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile with g++
        run: g++ dynamictable.cpp -o dynamictable.exe -static

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dynamictable-exe
          path: dynamictable.exe

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dynamictable.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
